### ISSUE TITLE
certificate verify failed running htgettoken from laptop

### ISSUE THREAD

**Issue by duncanmmacleod** [fermitools/htgettoken#33]
When attempting to run htgettoken from a conda environment on my laptop I get this:

```pytb
$ python htgettoken -a fermicloud543.fnal.gov -i ligo
Attempting OIDC authentication with https://fermicloud543.fnal.gov:8200

htgettoken: Initiating authentication to https://fermicloud543.fnal.gov:8200 failed: SSLError: certificate verify failed
```

This does _not_ happen from ldas-pcdev4.ligo.caltech.edu using the same set of conda packages. Is there some sort of domain/IP whitelisting for the LIGO issuer?

**Comment by DrDaveD** [comment]
No, it's probably a difference in the CA certificates installed on the client machine.  fermicloud543 uses a cert from the InCommon Grid CA so it is typically in /etc/grid-security/certificates when that is installed but it is not in the standard set of CA certs that come with operating systems.  Does that answer your question?

**Comment by duncanmmacleod** [comment]
> No, it's probably a difference in the CA certificates installed on the client machine. fermicloud543 uses a cert from the InCommon Grid CA so it is typically in /etc/grid-security/certificates when that is installed but it is not in the standard set of CA certs that come with operating systems. Does that answer your question?

Yes it does. What is the recommended solution for supporting users on their own laptops? Is there a documented bundle to install on each platform that includes the incommon CA certs?

**Comment by DrDaveD** [comment]
It depends on the deployment and what servers you want to connect to.  Servers that need to be accessed by lots of people in a VO from their laptops probably ought to be using a more standard CA.  This server is considered to be only for development and early testers and I figure that developers can get their hands on a CA bundle.

I know how to installed the bundle on [el7 & el8 from OSG](https://opensciencegrid.org/docs/common/ca/) but I don't know about other platforms.

**Comment by DrDaveD** [comment]
Oh, it's also in cvmfs at `/cvmfs/oasis.opensciencegrid.org/mis/certificates/` if you've got access to cvmfs.

**Comment by duncanmmacleod** [comment]
It sounds like LIGO need to spin up their own vault server, which I think you are already discussing with Ron et al.

**Comment by DrDaveD** [comment]
Oh, vault.ligo.org has already been installed for several months.  Try using that.
