### ISSUE TITLE
Add setuptools/poetry build script

### ISSUE THREAD

**Issue by duncanmmacleod** [fermitools/htgettoken#35]
It would be great to have a `setup.py` (setuptools) or `pyproject.toml` (for poetry) to make building/installing this 'package' on different platforms much easier (I'm thinking about Windows in particular here), rather than manually copying files to the target directories.

If @DrDaveD is open to that I can write up a prototype and propose a pull request.

**Comment by DrDaveD** [comment]
Sure, I'm open to including that.

**Comment by duncanmmacleod** [comment]
Great, would you like me to update the spec file et al to use that, or would you prefer to leave that as is (at least for now)?

**Comment by DrDaveD** [comment]
I definitely need the dependent packages to be predownloaded and included in the package, because the OSG koji builder doesn't allow downloads during rpmbuild.  If you can do that while still using setuptools I am open to that.

**Comment by duncanmmacleod** [comment]
Out of interest, what's the main reason for having the pyinstaller build a statically-compiled version of the script, rather than just installing a 'normal' python script?

**Comment by DrDaveD** [comment]
The reason was to avoid python 'dependency hell' and include all the dependencies in the package.  It was the easiest way I was able to find out how to do that.
