### ISSUE TITLE
kerberos workflow requires initial pass of OIDC workflow

### ISSUE THREAD

**Issue by astroclark** [fermitools/htgettoken#41]
Invoking `htgettoken` for the first time appears to always require an initial first pass through the browser workflow which generates the `~/.config/htgettoken/credkey-ligo-default` file, even when we have a valid kerberos ticket

E.g.:
```
$ kinit albert.einstein
Password for ...
$ htgettoken -v -a vault.ligo.org -i ligo
Attempting OIDC authentication with https://vault.ligo.org:8200

Complete the authentication via web browser at:
...
```
After which I can skip the browser step as normal in subsequent invocations.  

Is this known/expected behavior?  It generated some very minor confusion earlier where a new user was expecting to skip the browser step.

**Comment by DrDaveD** [comment]
Yes, absolutely it is required to do the OIDC flow once.  That's how vault gets the refresh token.  It also creates the ~/.config/htgettoken/credkey* file that tells htgettoken where to look for the refresh token in vault.  Does that answer the question?

**Comment by DrDaveD** [comment]
Kerberos is only used to renew a vault token after the first one has expired or been removed or replaced.
