### ISSUE TITLE
Add support for default issuer and vaultserver options

### ISSUE THREAD

**Issue by duncanmmacleod** [fermitools/htgettoken#42]
It would be great to be able to configure an environment with default values for the `-i/--issuer` and `-a/--vaultserver`  options, so that instead of running `htgettoken -a vault.ligo.org -i ligo`, users can run just 

```shell
htgettoken
```

Can support be added for `HTGETTOKEN_ISSUER` and `HTGETTOKEN_VAULTSERVER` environment variables, or similar?

**Comment by DrDaveD** [comment]
You can set them in $HTGETTOKENOPTS.

**Comment by duncanmmacleod** [comment]
> You can set them in $HTGETTOKENOPTS.

Missed that, sorry. For LIGO would the syntax be

```shell
HTGETTOKENOPTS="-a vault.ligo.org -i ligo"
```

? I think I have tested that locally and it works (including overrides), but confirmation would be appreciated.

**Comment by DrDaveD** [comment]
Yes that's right.
