### ISSUE TITLE
Should examples use real vault server?

### ISSUE THREAD

**Issue by retzkek** [fermitools/htgettoken#55]
I realize these are just examples, but htvault.fnal.gov does not exist (yet? maybe we should ask for a CNAME pointing to the production vault server?). If that's intended I'd suggest using an example.com domain. 

https://github.com/fermitools/htgettoken/blob/e2665380be497f0bf67bc9548821ffe428d55b9b/htgettoken.1#L364

ht @LTrestka

**Comment by DrDaveD** [comment]
Yeah I was a little surprised when the final name wasn't htvault.  I thought about asking for a CNAME but decided it wasn't worth it. Anyway you're probably right that an example.com would be better.
