### ISSUE TITLE
htgettoken should verify the scopes present in the returned token

### ISSUE THREAD

**Issue by jbasney** [fermitools/htgettoken#87]
Per the [WLCG Profile](https://github.com/WLCG-AuthZ-WG/common-jwt-profile/blob/master/profile.md#scope-based-capability-selection):

> If an entity is not entitled to a capability, the scope requested may be ignored by the server and the corresponding token may not have the corresponding claims; in this case, section 3.3 of RFC 6749 requires the token issuer to inform the client. A server may also return an error during the authorization request. **_Client software implementations should always verify the scopes present in the returned token._**

**Comment by jbasney** [comment]
I also submitted a related issue for OA4MP about returning an error if no scopes are approved: https://github.com/ncsa/oa4mp/issues/122

**Comment by DrDaveD** [comment]
htgettoken does not currently parse the JWT at all, it just stores it.  I think we need to view our "client software" with regard to the RFC as being all the applications that are involved, including vault, htgettoken, and the higher level applications.  I would leave this up to the higher level applications to verify.  vault and htgettoken are just pass-throughs for the JWT.
